### ISSUE TITLE
Binding to 0.0.0.0 is a bad practice 

### ISSUE THREAD

**Issue by akondasif** [SecGen/SecGen#10]
Greetings,

I am a security researcher, who is looking for security smells in Puppet scripts. I noticed instances of binding to 0.0.0.0. Binding an address to 0.0.0.0 indicates allowing connections from all IP addresses. I would like to draw attention to these instances. Binding to 0.0.0.0 may lead to denial of service attacks. Practitioners have reported how binding to 0.0.0.0 facilitated security issues for MySQL (https://serversforhackers.com/c/mysql-network-security), Memcached (https://news.ycombinator.com/item?id=16493480), and Kibana (https://www.elastic.co/guide/en/kibana/5.0/breaking-changes-5.0.html).    

I suggest to use a dedicated IP address other than 0.0.0.0. 

Any feedback is appreciated.  

Source: https://github.com/SecGen/SecGen/blob/master/modules/services/unix/ftp/vsftpd/manifests/params.pp

**Comment by LewisArdern** [comment]
Hi,
