### ISSUE TITLE
Issue with scenario

### ISSUE THREAD

**Issue by ashhad** [SecGen/SecGen#11]
I get the following error when running 
`ruby secgen.rb run`

I get the following error

Traceback (most recent call last):
	2: from modules/generators/compression/zip/secgen_local/local.rb:67:in `<main>'
	1: from /home/ashhad/Downloads/SecGen/lib/objects/local_string_encoder.rb:106:in `run'
modules/generators/compression/zip/secgen_local/local.rb:31:in `encode_all': uninitialized constant Zip::File (NameError)
Did you mean?  File
Module failed to run (ruby modules/generators/compression/zip/secgen_local/local.rb --b64 '--file_name=ZmxhZy50eHQ=' '--strings_to_leak=ZmxhZ3tlYjdlNGVlN2QyNDUwMGE4MDc1ZWFmNzgyYzcxNzA1Mn0=' )
Failed to resolve scenario.
No conflicts, but failed to resolve scenario -- this is a sign there is something wrong in the config (scenario / modules)
Please review the scenario -- something is wrong.

Any help will be appreciated. This is time critical.

**Comment by cliffe** [comment]
I think you are probably missing a gem related to the zip operation. You can just re-run the scenario, and chances are that it will choose a different configuration without using the zip feature. We would love to know how you are using SecGen (such that it's time critical).

**Comment by cliffe** [comment]
Try running:
gem install rubyzip

Should fix it.

**Comment by cliffe** [comment]
Oh, you should use the latest version of SecGen at https://github.com/cliffe/SecGen

**Comment by divyanshub1** [comment]
facing the same problem, tried with gem install rubyzip, no change

Module failed to run (bundle exec ruby modules/generators/compression/zip/secgen_local/local.rb)
Failed to resolve scenario.
No conflicts, but failed to resolve scenario -- this is a sign there is something wrong in the config (scenario / modules)
Please review the scenario -- something is wrong.

SecGen

**Comment by cliffe** [comment]
As noted above, please use the latest version of SecGen at https://github.com/cliffe/SecGen

**Comment by divyanshub1** [comment]
i have tried with the same link as  SecGen at https://github.com/cliffe/SecGen, i am using ubunutu 16.04 getting error 

error 1- Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'jplana/debian_wheezy_puppet' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'jplana/debian_wheezy_puppet'
    default: URL: https://vagrantcloud.com/jplana/debian_wheezy_puppet
The box 'jplana/debian_wheezy_puppet' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: https://vagrantcloud.com/jplana/debian_wheezy_puppet
Error: Failed writing body (0 != 557)

**Comment by divyanshub1** [comment]
After running the commands provided , i am using git clone https://github.com/cliffe/secgen to get the secgen folder , which is not avialable on the page
