### ISSUE TITLE
Issue with Secgen when creating VM

### ISSUE THREAD

**Issue by Shadow2xx** [SecGen/SecGen#7]
Hello everyone!

I just stepped over SecGen and I wanted to tried it out on my Linux GNU.

I installed SecGen and VirualBox. But when I run the command : ruby secgen.rb run it runs all fine. Until it shows: "Bringing machine 'storage_server' up with 'virtualbox' provider..."

Sounds good? No, Iet it load like 3 hours and more... can anyone help me?

Thanks:D

**Comment by Shadow2xx** [comment]
Sorry for my broken english^^

**Comment by LocHT** [comment]
I fixed this by doing `apt-get remove vagrant` then I installed it directly from the website, i also did `gem cleanup` although I don;'t think that had much effect.

**Comment by cliffe** [comment]
Great. Please note the latest version of SecGen is at github.com/cliffe/secgen

**Comment by Shadow2xx** [comment]
Yes, I am using Debian


WandererHTP <notifications@github.com> schrieb am Fr. 20. Okt. 2017 um
00:00:

**Comment by Shadow2xx** [comment]
Thank you for your replies
